### ISSUE TITLE
Phoebe public server down?

### ISSUE THREAD

**Issue by contactgillen** [phoebe-project/phoebe2-ui#17]
I was unable to get the desktop server running, and I'm wondering if the public server is down? I've been trying to connect from the desktop UI and browser and it hasn't let me in.

**Comment by kecnry** [comment]
Yes, unfortunately the public server has been down for a few weeks.  We will try to get it up and running as soon as we can (or at least add a note to the website somewhere).  Sorry for the inconvenience!

-Kyle

**Comment by contactgillen** [comment]
Thanks for the reply!

**Comment by contactgillen** [comment]
Actually I have a follow up question. . . is it possible for me to get a server running on my own machine, or is it a global problem with the software?

**Comment by kecnry** [comment]
Yes, you should be able to run a local instance still, you'll just need to have phoebe installed on your own machine and then can launch the server with `phoebe-server` to run it on localhost.  See the [server instructions](http://phoebe-project.org/clients#server) for (a few) more details... or feel free to ask if you run into any questions/problems!

**Comment by contactgillen** [comment]
God bless you for getting back to me so fast. Here's where I am with the installation: 

![phoebe sadness](https://user-images.githubusercontent.com/100183386/179824090-edb5f123-ba02-4814-925e-95ad185fb99b.png)

I tried changing versions of flask-socketio and whatnot but can't get them to cooperate with the software. Any advice?

**Comment by kecnry** [comment]
Can you send me the versions of each of those packages that you have installed and I can try to look into it?  

I have seen this happen before though - installing in a fresh environment (virtual or conda) often helps make these dependency conflicts a lot easier to resolve (you might have other packages which are requesting different versions and causing conflicts).

**Comment by kecnry** [comment]
The public server should be back online - sorry it was down so long!
