### ISSUE TITLE
06 Aug 2022 - failed to connect to Phoebe server

### ISSUE THREAD

**Issue by DmytroTvardovskyi** [phoebe-project/phoebe2-ui#18]
Hello!
I'm a new user of Phoebe and I tried to use web version first. I launched it on 6 of August 2022 at 1 AM MDT (7 AM UTC). I have been waiting for server connection for more than an 30 minutes. However, nothing happen. Is server down or anything else happen with it?
Thank you for your time and assistance!

Best wishes, 
Dmytro.

**Comment by kecnry** [comment]
Yes, the public server is currently down. Unfortunately we cannot provide an estimate for when we'll get it back up and running.

In the meantime, you can still use the web or desktop version with you own instance of the server (see instructions on the website or the discussion in #17 for more details).

**Comment by DmytroTvardovskyi** [comment]
Dear Kyle,
Thank you for your reply. I'll wait to server is up again, that's the most
comfortable solution for me. Fortunatelly, that's not urgent.

Best regards,
Dmytro.

**Comment by carlo-hue** [comment]
Hello!
I'm trying to use web version of phoebe but I can't get connection with server.phoebe-project.org...is the the server still down?

thank you very much
Best regards
Carlo

**Comment by DmytroTvardovskyi** [comment]
Hello Carlo!
I have the same stuff, as ~5 month ago - it's trying to connect to a server
for about 10 minutes with no actual success.
Thus, I think, the server is still down. There are also problems with
the Desktop client and Python package - none of them is working properly.
If you require some assistance to make it operational - do not hesitate to
contact me. Currently, there are several students of mine, who are
researching eclipsing binaries using TESS data and they want to do physical
modelling of their stars.
So, this collaboration could be profitable for both our teams.

Best wishes and Happy New Year!
Dmytro

[image: image.png]

**Comment by kecnry** [comment]
Yes, the public server is still down for the foreseeable future.  I'll update the website soon to no longer link to the public server version to avoid any additional confusion.  Right now our priority without anyone currently able to commit significant hours to development is maintenance and addressing any critical bugs in the python package - if you know of any issues that aren't reported or there are any that are preventing you from being able to do science, please do let us know (file or comment on [issues on the main phoebe2 repository](https://github.com/phoebe-project/phoebe2/issues)) so that we can prioritize those.

**Comment by DmytroTvardovskyi** [comment]
Hello Kyle!
Thank you for your email.
Yeah, here are some not-yet-reported issues with the Python version. Do you
need any assistance to speed up the debugging process?
And another question about desktop client: will it be available or also
removed from the website? There are also some issues there.

Best wishes,
Dmytro.

**Comment by kecnry** [comment]
Please do report any issues to the relevant issue trackers (phoebe2 or phoebe2-ui) and let us know if they're just annoyances or actually blocking you from being able to use phoebe so we can try to prioritize them.  Scripts/steps to reproduce are always helpful to quickly address and test the bugs.  If you (or anyone) is interested in actually trying to fix bugs, PRs are also welcome and I'd be happy to help step anyone through that process.  Thanks!

**Comment by kecnry** [comment]
The public server should be back online - sorry it was down so long!

**Comment by carlo-hue** [comment]
Hi Kyle,
I'm sorry to reply so late, due to already overcome problems.
Thank you very much
carlo

Il giorno ven 3 feb 2023 alle ore 14:12 Kyle Conroy <
***@***.***> ha scritto:

**Comment by carlo-hue** [comment]
Hello Dmytro,

I'm sorry to reply so late, but I had problems that are now outdated.

Thank you for your availability, which we will certainly take advantage of.
I belong to an amateur astronomy association that has undertaken a research
activity for variables and exoplanets for a few months. For this purpose,
we have developed our own sw tool for the processing and analysis of light
curves using both data obtained through our social instrument (we have a
fully remote controlled social telescope) and existing survey data, mainly
ASAS and ZTF. So far, we've discovered about ten new variables.

We started using TESS data about a month ago and we are developing our own
processing pipeline, integrated into the aforementioned software tool. I
would certainly be interested in a comparison to understand if what we do
is effective and goes in the right direction!

Thanks and sorry again for the delay
Carlo


Il giorno dom 1 gen 2023 alle ore 21:12 DmytroTvardovskyi <
***@***.***> ha scritto:

> Hello Carlo!
> I have the same stuff, as ~5 month ago - it's trying to connect to a server
> for about 10 minutes with no actual success.
> Thus, I think, the server is still down. There are also problems with
> the Desktop client and Python package - none of them is working properly.
> If you require some assistance to make it operational - do not hesitate to
> contact me. Currently, there are several students of mine, who are
> researching eclipsing binaries using TESS data and they want to do physical
> modelling of their stars.
> So, this collaboration could be profitable for both our teams.
>
> Best wishes and Happy New Year!
> Dmytro
>
> [image: image.png]
>

**Comment by carlo-hue** [comment]
Hello  Dmytro,

finally, we started using TESS data for a couple of months ago for our
search for variables carried out within our association
amateur astronomy. In the context of which we have already noted some
unknown variable stars.

However, we have some doubts and questions, I ask you if you can kindly
direct me to find an answer.

One of the "hot topics" concerns TPFs. Currently we download the TPF data
using Lightkurve API:
-  search_result = lk.search_tesscut(ra_de, sector=number_sector)
-  tpf = search_result.download(cutout_size=dimens_cut)

We are detecting what seem to us inconsistencies in the timing of stars in
different sectors. We are currently analyzing the star
239638941527789568, with TIC 192772896, present in sectors 18 and 58 and it
seems to us that the times of the two sectors are not perfectly phased... I
attach the PhasePlot with the contribution of both sectors:the period
coincides, the phase does not...

Question: is it necessary to apply some correction in the times of TPF.fits
obtained with LightKurve primitives? (for example, it is
necessary a correction to be made by applying the obtainable data from
TIMECORR or are the times in the TPF already correct?)

Thanks in advance for the support you can give us

a greeting
Carlo





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_1441950274779235754_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mer 1 mar 2023 alle ore 00:13 carlo marino ***@***.***>
ha scritto:

> Hello Dmytro,
>
> I'm sorry to reply so late, but I had problems that are now outdated.
>
> Thank you for your availability, which we will certainly take advantage of.
> I belong to an amateur astronomy association that has undertaken a
> research activity for variables and exoplanets for a few months. For this
> purpose, we have developed our own sw tool for the processing and analysis
> of light curves using both data obtained through our social instrument (we
> have a fully remote controlled social telescope) and existing survey data,
> mainly ASAS and ZTF. So far, we've discovered about ten new variables.
>
> We started using TESS data about a month ago and we are developing our own
> processing pipeline, integrated into the aforementioned software tool. I
> would certainly be interested in a comparison to understand if what we do
> is effective and goes in the right direction!
>
> Thanks and sorry again for the delay
> Carlo
>
>
> Il giorno dom 1 gen 2023 alle ore 21:12 DmytroTvardovskyi <
> ***@***.***> ha scritto:
>
>> Hello Carlo!
>> I have the same stuff, as ~5 month ago - it's trying to connect to a
>> server
>> for about 10 minutes with no actual success.
>> Thus, I think, the server is still down. There are also problems with
>> the Desktop client and Python package - none of them is working properly.
>> If you require some assistance to make it operational - do not hesitate to
>> contact me. Currently, there are several students of mine, who are
>> researching eclipsing binaries using TESS data and they want to do
>> physical
>> modelling of their stars.
>> So, this collaboration could be profitable for both our teams.
>>
>> Best wishes and Happy New Year!
>> Dmytro
>>
>> [image: image.png]
>>

**Comment by DmytroTvardovskyi** [comment]
Hello, Carlo!
Amateur astronomy search is a good thing to do and I'm really appreciated
to hear back from you about your first results!
Currently me and my team are running a project with TESS data analysis with
71 students in total. So, as you can imagine, we need a lot of data for
their research. Thus, I use the code for downloading the data
sector-by-sector and now we have downloaded lightcurvers for all 61 sectors
(~2.7 TB). And then we apply another code to convert .fits files with raw
data into simple two-column data sets (another ~0.8 TB). We aren't doing
any corrections automatically because they are not significant for our type
of analysis.
If you and your team would like to make an online meeting where we can both
share the knowledge of how-to-do this stuff. I will be really glad to see
you! And I can share those codes with your team if necessary.
In addition, we are going to use your Phoebe-server for binary simulations
in late-April, so I hope it's ready for ~70 additional users 😅

Best wishes and see you soon.
Dmytro.

**Comment by carlo-hue** [comment]
Hello, 
I have a very basic question....I'm trying to use the web client, I selected default binary, added a dataset (kind=lc without loading data) and launched the run compute....but I can't see anything in the picture ...I think I'm doing something fundamentally wrong...

Hy Dmytro,  I'm sorry I didn't reply sooner, a lot of work (not astromic....). However, we continued too, even if not quickly, We discovered various variable stars, now we too would like to deepen the study of some binary systems that we have found, and, as you can see, we're  starting to study....
For online meeting, that would be great, if you were still available

Best wishes

**Comment by kecnry** [comment]
> I'm trying to use the web client, I selected default binary, added a dataset (kind=lc without loading data) and launched the run compute....but I can't see anything in the picture ...I think I'm doing something fundamentally wrong...

Please create a new issue if you're still seeing this with any details you can provide (does the model compute successfully?  is there a figure image but it's just blank or none is being created at all?).  This issue has already been fixed/closed and its hard to track when multiple issues are reported in the same thread.  Thanks!
