### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by margaretStreamer** [phoebe-project/phoebe2-ui#19]
I've installed PHOEBE 2.4 on a windows 10/11 computer in a conda environment.
The installation was successful but on trying to run in a jupyter notebook I get the following error message:
import phoebe
from phoebe import u # units
----------------------------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import phoebe
      2 from phoebe import u

File ~\anaconda3\envs\phoebe24\lib\site-packages\phoebe\__init__.py:378
    376 from .dependencies.distl import gaussian, gaussian_around, normal, boxcar, uniform, uniform_around, histogram_from_bins, histogram_from_data, mvgaussian, mvhistogram_from_data
    377 from .atmospheres.passbands import install_passband, uninstall_passband, uninstall_all_passbands, download_passband, list_passband_online_history, update_passband_available, update_passband, update_all_passbands, list_all_update_passbands_available, list_online_passbands, list_installed_passbands, list_passbands, list_passband_directories, get_passband
--> 378 from .parameters import hierarchy, component, compute, constraint, dataset, feature, figure, solver, server
    379 from .frontend.bundle import Bundle
    380 from .backend import backends as _backends

File ~\anaconda3\envs\phoebe24\lib\site-packages\phoebe\parameters\__init__.py:2
----> 2 from .parameters import *

File ~\anaconda3\envs\phoebe24\lib\site-packages\phoebe\parameters\parameters.py:33
     31 from fnmatch import fnmatch
     32 from copy import deepcopy as _deepcopy
---> 33 import readline
     34 import numpy as np
     35 from scipy.stats import norm as _norm

ModuleNotFoundError: No module named 'readline'

**Comment by kecnry** [comment]
Hi Margaret!  You'll need to install readline using pip within the conda environment (for some reason non-anaconda installations of conda in windows does not include readline, even though it is standard elsewhere).  If for some reason this doesn't fix things for you, feel free to re-open the issue.

-Kyle

**Comment by margaretStreamer** [comment]
Hi Kyle, 
I needed to install pyreadline not readline.  
Took me a while to search and go through all the errors along the way.
Hopefully phoebe will work from now on.
Cheers,
Margaret

**Comment by kecnry** [comment]
Ok, thanks for the update - they will be very useful if anybody else runs into the same thing.  Let it know if you run into any other problems or questions.
