### ISSUE TITLE
web client

### ISSUE THREAD

**Issue by carlo-hue** [phoebe-project/phoebe2-ui#21]
Hi,
I'm trying to use the web client, I selected default binary, added a dataset (kind=lc without loading data) and launched the run compute....but I can't see anything in the picture ...the model computed successfully, there is a figure image but it does contains anything...

Am I doing something fundamentally wrong?

thanks

**Comment by kecnry** [comment]
Just to clarify, you're using `ui.phoebe-project.org` but with the server running on your own machine on localhost?  Can you post a screenshot of what you're seeing (is there a blank white image, or just a figure entry but no actual png displayed at all)?

**Comment by carlo-hue** [comment]
I lauched phoebe web client via following command
![image](https://github.com/phoebe-project/phoebe2-ui/assets/101313374/ebd5a6ba-cc49-4856-9993-e401e68bcbfa)

then Igot following response
![image](https://github.com/phoebe-project/phoebe2-ui/assets/101313374/3e29f0b0-9fba-4a73-85c0-14800aadc5d6)

today I'm not able to go on (connectivity problem?), but a week ago I could select bundle for binary default and launh compute. I could obtain figure entry but without png dispalyed

**Comment by kecnry** [comment]
The public UI server will probably remain down for a while as we work on migrating it to a new server, we apologize for the inconvenience and will update back here when it's back and hopefully will be more reliably available after that.

**Comment by kecnry** [comment]
The server is back up (and hopefully should have _much_ less downtime going forward).  Sorry for the inconvenience!
