### ISSUE TITLE
Phoebe UI stuck at install phoebe server locally

### ISSUE THREAD

**Issue by XRByte** [phoebe-project/phoebe2-ui#26]
I am using ubuntu-24.04 and python 3.12. I have installed phoebe using pip but when I enter phoebe-server in the terminal, it's showing command not found. When I open the phoebe-UI2 using phoebe command, it gets stuck at "Install phoebe server locally" and I am unable to launch the phoebe-server manually.

**Comment by kecnry** [comment]
Sorry about that - looks like this was broken by phoebe 2.4.12.  We'll try to get that fixed.  In the meantime, can you try installing phoebe 2.4.11 to install the server, at which point you should be able to upgrade to the latest version of phoebe and still have the server installed.

**Comment by XRByte** [comment]
Thanks for the information. I have installed phoebe 2.4.11 and the server as well as the UI are working fine. However, when I am upgrading to the latest version, the previous version is getting uninstalled and the phoebe server is no longer available.

**Comment by kecnry** [comment]
Ok, we'll update here when we get a fix out, in the meantime you should be safe to use 2.4.11 - you can see the [changelog](https://github.com/phoebe-project/phoebe2?tab=readme-ov-file#changelog) for changes since then in case there are known bugs that would affect you.

**Comment by XRByte** [comment]
Thanks for the information.

**Comment by kecnry** [comment]
This should now be fixed in phoebe 2.4.15 via https://github.com/phoebe-project/phoebe2/pull/929

**Comment by XRByte** [comment]
Thanks.
