### ISSUE TITLE
"Name ferr is not defined"

### ISSUE THREAD

**Issue by kathmcp** [phoebe-project/phoebe2-ui#9]
Hi, I am trying to run a contact binary model using the PHOEBE web client, and I keep getting the error "Name ferr is not defined". This is my first attempt so it's quite possible I am missing something. 

Also, I am not sure if I will need to flip constraints or not yet, but if I do, is this possible with the web UI, or would I need to use Python?

Any help would be much appreciated. Thanks!

**Comment by kecnry** [comment]
Are you using ui.phoebe-project.org?  If not, can you please let me know the UI and phoebe version (shown in the lower right and lower left, respectively)?

I can't reproduce the error, so can you please try to reproduce it from scratch and let me know the steps you take that give this error message?

You can flip constraints from the UI.  The constraint parameters themselves are hidden by default, you can view them in one of two ways:

1. Unhide all constraints under the "show options" menu in the top-left:
![image](https://user-images.githubusercontent.com/877591/124757475-9ef5d280-defb-11eb-8846-147d9cdf64f5.png)

2. or follow the link to a constraint from a constrained parameter (click the empty square to "pin" the parameter and then again to follow the link to the constraint parameter itself):
![constraint_show](https://user-images.githubusercontent.com/877591/124759212-66ef8f00-defd-11eb-8640-109267ac957d.png)


You can then click on the "value" of the constraint parameter and choose which parameter you want to be constrained in its place.
![constraint_edit](https://user-images.githubusercontent.com/877591/124759665-e3826d80-defd-11eb-90f4-7d1a539b8789.png)
![constraint_edit](https://user-images.githubusercontent.com/877591/124759876-247a8200-defe-11eb-8518-ac64de8f331c.png)

**Comment by kathmcp** [comment]
Hi,

Thanks for the information on flipping constraints, that's really helpful.

I am using ui.phoebe-project.org, in Google Chrome, and it gives UI and Phoebe versions of 1.0.0 and 2.3.44 in the lower right and left.

I start with a default binary, add light curves (times, fluxes and flux errors) from a csv file, enter the exposure time, filter type, set the period, and add an envelope. I leave everything else as default values for now. When I run compute, it initially says success, then it says the error "Name ferr is not defined" when it gets to the attached screen.

If I run it leaving the period at the default of 1.0d, the error doesn't appear. When it gets to the screen below, it does initially have a red skull and crossbones against the detached_job@latest@model, but then this changes to loaded and 3 other parameters appear below it.

I have also tried changing the rest of the inputs from default to what I think are correct for my system, but it still comes up with this error (when I use the correct period).
![ferrError](https://user-images.githubusercontent.com/81473857/125065108-57ad4480-e0a9-11eb-9190-8005b0b6d96b.PNG)

Hope this helps! Thanks again.

**Comment by kathmcp** [comment]
Hi again,

I just tried it again, with all my calculated inputs for my system, and the error has disappeared! Thanks again anyway!

**Comment by kecnry** [comment]
Ok, I can't seem to reproduce the "ferr" message.  As long as it doesn't crash and still provides the synthetic model, then I don't think its anything to worry about too much.  

The skull and crossbones just allows you to cancel a job that is currently running (the symbol will probably change in a future release since it seems to cause confusion).

If you have a contact system, I would suggest starting with a contact system instead of adding an envelope (otherwise you need to [update the hierarchy parameter in python](http://phoebe-project.org/docs/2.3/tutorials/contact_binary_hierarchy), as that is not supported in the UI yet).  In fact, I created a separate issue (#10) to remove the ability to add components from the UI in the meantime.

**Comment by kathmcp** [comment]
OK thanks for that. I thought by adding an envelope I was making it a contact binary. How do I start with a contact system from the web UI?

**Comment by kecnry** [comment]
Yep, I'll try to make that more clear in the UI in the future.  If you click the arrow that appears on the right when hovering over "default binary" you'll get options for detached, semi-detached, or contact.

**Comment by kathmcp** [comment]
Fantastic, thanks again! 👍
